name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare release assets
        run: |
          mkdir -p dist
          zip -r dist/tracking_numbers.zip custom_components/tracking_numbers \
            -x '*/__pycache__/*' '*.pyc' '*.pyo' '*/.DS_Store' '*sensor.py.backup' '*email.log'
          cp hacs.json dist/hacs.json

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/tracking_numbers.zip
            dist/hacs.json
